export default {
  header: "Bio",
  page: "Bio",
  paragraphs: [
    {
      paragraph1:
        "What exactly did Hippocrates, the Greek founder of western medicine, really have to say about food and health? Dr. Goodfood's team dug into it, just for you! Let food be thy medicine, and let medicine be thy food.”  This famous quote is often attributed to Hippocrates. But, as research by Diana Cardenas in 2013 shows, this quote can not be found anywhere in Hippocrates' writings. Diana Cardenas discovered that the quote started to emerge from 1926 onwards, and really started to get popular in the 1970s. There are good reasons for the quote to go round, though. Hippocrates considered nutrition one of the main tools that a doctor can use. More than that, dietary measures play a lead part in the original oath of Hippocrates. In modern translations of the oath, the central importance of diet is often somewhat hidden. English Wikipedia for example turns it into: “I will use treatment to help the sick according to my ability and judgment, but never with a view to injury and wrong-doing. But the original Greek oath, literally translated, says: “I will apply dietetic and lifestyle measures to help the sick to my best ability and judgment; I will protect them from harm and injustice.The dietetic and lifestyle measures are just one word in Greek, διαιτήμασί (pronounce as deaytimasy). You may recognize the word diet in there. It means as much as a lifestyle regime, with a focus on diet. Exercise is also part of it. Sometimes it is just translated as: dietetic measures. In another text by Hippocrates, “De Alimento”, there's another statement about food, which reads: “In  food excellent medicine can be found, in food bad medicine can be found; good and bad are relative. With some imagination this can be read as: some foods can cure you, other foods can make you sicker; the effect can vary case by case. Hippocrates did not see food and medicine as one and the same thing. But it's obvious from Hippocrates writings, that diet and lifestyle regime were at the center of his thoughts about the responsibilities of a doctor and the tools for treatment that a doctor can use. Exercise was also part of it. Hippocrates was a strong proponent of going on walks. Walking is a natural exercise, more than any other form of physical exercise. Especially a stroll after dinner was considered to be very beneficent by Hippocrates. The recipes by Dr. Goodfood, Anna Kruyswijk, which help you improve your own health, were designed in the true spirit of Hippocrates. And if you are done eating, don't forget to take a nice walk.  It prevents fattening of the stomach, said Hippocrates around 400 BC. Yours truly, Dr. Goodfood teamWhen incorporated into a well-balanced diet, superfoods can promote heart health, weight loss, improve energy levels and even reduce the effects of aging. Antioxidants found in many superfoods may help prevent cancer, while healthy fats can reduce your risk of heart disease."
    }
  ]
};
